version: '2'
services:
    jhipster5test-app:
        image: jhipster5test
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster5test-mysql:3306/jhipster5test?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster5test-mysql:
        extends:
            file: mysql.yml
            service: jhipster5test-mysql
